### ISSUE TITLE
Python 3.8+: NameError: name 'cache' is not defined

### ISSUE THREAD

**Issue by hugovk** [byexamples/byexample#116]
**Describe the bug**
A clear and concise description of what the bug is followed by the steps to reproduce it:
1. With Python 3.8, `pip install byexample` on macOS
2. Run `byexample -l python README.md`

```console
$ byexample -l python README.md
Process 0:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/common.py", line 191, in human_exceptions
    yield o
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/byexample.py", line 20, in execute_examples
    cache.synced(label=filename), \
NameError: name 'cache' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/jobs.py", line 24, in worker
    output.put(func(item, sigint_handler))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/byexample.py", line 26, in execute_examples
    return executor.execute(examples, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/common.py", line 201, in human_exceptions
    rlog.exception(msg=None, where=where_default)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1469, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/__init__.py", line 1463, in error
    self._log(ERROR, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'where'
^C^C^C^C^C^C^C^C^C^C^C^C^C^C[1]    44820 terminated  byexample -l python README.md
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
Needed to kill the Python process in Activity Monitor.

**Expected behavior**

Runs tests in the `README.md`

**byexample version**
Run ``byexample -V`` to know the version of ``byexample`` and ``python``.

```console
byexample -V
byexample 9.1.0 (Python 3.8.3) - GNU GPLv3

Write snippets of code in C++, Python, Ruby, and others as documentation and execute them as regression tests.

Copyright (C) Di Paola Martin - https://byexamples.github.io

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

I enabled Python 3.8 and 3.9-dev on the CI in my fork, and they failed (can ignore 3.10-dev, it fails due to dependencies not being ready yet):

https://travis-ci.com/github/hugovk/byexample/builds/171355524

**Comment by eldipa** [comment]
Hi, thank you for the report. It seems that there are two issues, close but unrelated:
 - `cache` is not defined
 - some tests fail in Python 3.8 and 3.9

For the latter, the problem is that  `byexample` uses a dark and undocumented feature of Python that is not longer available.
The feature is disabled by default and only enabled for testing so I disabled it for Python 3.8 and superior (release [9.1.1](https://github.com/byexamples/byexample/releases/tag/9.1.1)

The former issue is more weird. It says that `cache` is not defined. The variable is declared as global and the `main` function defines it *before* calling `execute_examples` where it fails.

https://github.com/byexamples/byexample/blob/9.1.0/byexample/byexample.py

Could you try to run the following snippet?
```python
import contextlib                                                                                                              
class Cache:                                                                                                                   
    @contextlib.contextmanager                                                                                                 
    def activated(self, val):                                                                                                  
        print("activating", val)                                                                                               
        try:                                                                                                                   
            yield self                                                                                                         
        finally:                                                                                                               
            print("deactivating", val)                                                                                         
                                                                                                                               
def bar():                                                                                                                     
    global cache                                                                                                               
    with cache.activated('bar'):                                                                                               
        print("I'm bar")                                                                                                       
                                                                                                                               
def foo():                                                                                                                     
    global cache                                                                                                               
    cache = Cache()                                                                                                            
    with cache.activated('foo'):                                                                                               
        print("I'm foo")                                                                                                       
        bar()                                                                                                                  
                                                                                                                               
if __name__ == '__main__':                                                                                                     
    foo()
```
Basically it does the same that `byexample` but with much less code. I'm suspecting an error in the Python interpreter that you have installed but we need a little evidence (I tested `byexample 9.1.1` in Python 3.8 it works so that's why I'm suspecting this) 

And thank you for your time filling the bug report!

**Comment by hugovk** [comment]
With that snippet I get this with Python 3.8.3:
```
activating foo
I'm foo
activating bar
I'm bar
deactivating bar
deactivating foo
```

**Comment by eldipa** [comment]
And that's the correct output....

It took me a while but I found at least the source of the problem.

`byexample` runs the tests in a separated worker using `multiprocessing`.
It executes `execute_examples` in a subprocess spawned from [here](https://github.com/byexamples/byexample/blob/9.1.1/byexample/byexample.py#L60).

`multiprocessing` has three methods to spawn a process: `spawn`, `fork` and `forkserver` and the default for macOS changed from `fork` to `spawn` in Python 3.8. [changes in multiprocessing](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)

I managed to run `byexample` in macOS using `travis`. I copy the config for future references:
```
os: osx                                                                                                                        
language: sh                                                                                                                   
addons:                                                                                                                        
homebrew:                                                                                                                      
  update: true                                                                                                                 
  packages: python3                                                                                                            
before_install:                                                                                                                
  - pip3 install virtualenv                                                                                                    
  - virtualenv -p python3 ~/venv                                                                                               
  - source ~/venv/bin/activate
```
Unfortunately the installed version of python is 3.7 so to validate cause of the error I put this line just at the begin of the `main` function (with `multiprocessing` imported before):
```
multiprocessing.set_start_method('spawn')
```
And voila! `NameError: name 'cache' is not defined` https://travis-ci.org/github/byexamples/byexample/builds/698626680

Changing `spawn` by `fork` "solves" the problem but [open others](https://bugs.python.org/issue33725) of course.

And switching to `spawn` or even `forkserver` is not trivial. When `fork` mode is used, a subprocess is a exact copy of the parent process so objects like `cache`, `harvester` are inherited and available as copies.
Using another start mode will require to change that and pass the objects explicitly with a Queue probably; my concern however is with the console and logging.

@hugovk could you confirm me if the following steps fix the issue?:
 1. Import `multiprocessing` in `/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/byexample/byexample.py`
 1. Add `multiprocessing.set_start_method('fork')` at the begin of the `main` function, after the `global` statement in the same file than above.
